# Generated by Django 5.1 on 2024-09-05 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('photo', models.FileField(upload_to='')),
                ('admno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField(null=True)),
                ('parentname', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('contactno', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(default='student', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('contactno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(default='teacher', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('contactno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(default='parent', max_length=100)),
                ('studadmno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eduapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='notificationparent',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('currentdate', models.DateField(auto_now_add=True, null=True)),
                ('notification', models.CharField(max_length=100)),
                ('studentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eduapp.student')),
                ('teacherid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eduapp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('notification', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eduapp.student')),
                ('teacherid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eduapp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Noteupload',
            fields=[
                ('noteupload_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('uploadnotes', models.FileField(upload_to='')),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('teacherid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eduapp.teacher')),
            ],
        ),
    ]
